import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>passmark</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="images/logo/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <section>
          <header>
            <nav>
              <nav class="navbar navbar-expand-lg">
                <div class="container">
                  <div class="nav-div-0">
                    <p>
                      <span>
                        <a class="nav-0-link nav-1-link0" href="#courses">
                          Courses
                        </a>
                      </span>
                      <span>
                        <a class="nav-0-link nav-1-link1" href="#instructors">
                          Teachers
                        </a>
                      </span>
                      <span>
                        <a class="nav-0-link nav-1-link2" href="#testimonies">
                          Comments
                        </a>{" "}
                      </span>
                    </p>
                  </div>
                  <div class="nav-div-1">
                    <p class="logo-text">
                      <span class="logo-span0">Pass</span>
                      <i class="fa-solid fa-circle-check logo-icon"></i>
                      <span class="logo-span0">mark</span>
                    </p>
                  </div>
                  <div class="nav-div-2">
                    <Link href="/Signin">
                      <button type="button" class="nav-button nav-sign-in">
                        Sign in
                      </button>
                    </Link>
                    <Link href="/Signup">
                      <button type="button" class="nav-button nav-sign-up">
                        Sign up
                      </button>
                    </Link>
                  </div>
                </div>
              </nav>
            </nav>
          </header>

          {/* <!-- First DIV START --> */}
          <div class="first-div container">
            <div class="row">
              <div class="first-div-col0 col-md">
                <p class="first-div-title-text">your e-learning partner</p>
                <p class="first-div-header">
                  Online Learning Now In Your Finger Tips
                </p>
                <p class="first-div-sub-header">
                  Passmark is an online learning platform that offers various
                  premium courses for your skill development.
                </p>
                <div class="first-div-buttons">
                  <Link href="Signup">
                    <button type="button" class="nav-button try-now-button">
                      Try now
                    </button>
                  </Link>
                  <a href="sign-up.html">
                    <button type="button" class="nav-button play-video-button">
                      <i class="fa-solid fa-play play-video-icon"></i>Play video
                    </button>
                  </a>
                </div>
              </div>
              <div class="first-div-col1 col-md">
                <img
                  class="first-div-gif"
                  src="images\landing-page-images\e-learning.gif"
                  alt="e-learning gif"
                />
              </div>
            </div>
          </div>
          {/* <!-- FIRST DIV END  --> */}

          {/* <!-- SECOND DIV START --> */}
          <div class="second-div container" id="courses">
            <p class="section-header second-div-header">Our Popular Courses</p>
            <div class="second-div-card-div row row-cols-1 row-cols-sm-2 row-cols-md-4 row-cols-lg-6 g-4">
              <div class="second-div-card col-md-3">
                <img
                  class="second-div-icon"
                  src="images\landing-page-images\business-vector.png"
                  alt="business-icon"
                />
                <p class="second-div-text">
                  Business <br /> marketing
                </p>
              </div>
              <div class="second-div-card  col-md-3">
                <img
                  class="second-div-icon"
                  src="images\landing-page-images\design-vector.png"
                  alt="design-icon"
                />
                <p class="second-div-text">
                  UI/UX <br /> design
                </p>
              </div>
              <div class="second-div-card  col-md-3">
                <img
                  class="second-div-icon"
                  src="images\landing-page-images\writing-vector.png"
                  alt="writing-icon"
                />
                <p class="second-div-text">
                  Content <br /> writing
                </p>
              </div>
              <div class="second-div-card  col-md-3">
                <img
                  class="second-div-icon"
                  src="images\landing-page-images\web-development-vector.png"
                  alt="web-dev-icon"
                />
                <p class="second-div-text">
                  Website <br /> development
                </p>
              </div>
              <div class="second-div-card  col-md-3">
                <img
                  class="second-div-icon"
                  src="images\landing-page-images\storage-vector.png"
                  alt="cloud-storage-icon"
                />
                <p class="second-div-text">
                  Cloud <br /> storage
                </p>
              </div>
            </div>
          </div>
          {/* <!-- SECOND DIV END -->

    <!-- THIRD DIV START --> */}
          <div class="third-div container">
            <div class="row">
              <div class="col-12 col-lg-6 third-div-col0">
                <img
                  class="third-div-img"
                  src="images\landing-page-images\scale-up.png"
                  alt="scale-up.jpg"
                />
              </div>
              <div class="col-12 col-lg-6 third-div-col1">
                <p class="section-header third-div-header">
                  Various types of courses to upscale your skill
                </p>
                <p class="section-text third-div-text">
                  Online learning allows the student and teacher to set their
                  own learning pace, and there's the added flexibility of
                  setting a schedule tat fits everyone.
                </p>
                <Link href="/Signup">
                  <button type="button" class="nav-button try-now-button">
                    <i class="fa-solid fa-fade fa-plus third-div-icon"></i>
                    Enroll now
                  </button>
                </Link>
              </div>
            </div>
          </div>
          {/* <!--THIRD DIV END  -->

    <!-- FORTH DIV START  --> */}
          <div class="forth-div container" id="instructors">
            <p class="section-header forth-div-header">
              Our Expert{" "}
              <span class="forth-div-header-colored">Instructor</span>
            </p>
            <div class="forth-div-card-div">
              <div class="row">
                <div class="col-12 col-md-6 col-lg-3">
                  <div class="forth-div-card card">
                    <img
                      src="images\landing-page-images\design-instructor.jpg"
                      class="forth-div-card-img card-img-top"
                      alt="..."
                    />
                    <div class="forth-div-card-body">
                      <p class="forth-div-card-header">
                        Kafayat Asus{" "}
                        <span class="forth-div-card-icon">
                          <i class="fa-brands fa-figma"></i>
                        </span>
                      </p>
                      <p class="forth-div-card-sub-header">UI/UX Designer</p>
                    </div>
                  </div>
                </div>
                <div class="col-12 col-md-6 col-lg-3">
                  <div class="forth-div-card card">
                    <img
                      src="images\landing-page-images\developer-instructor.jpg"
                      class="forth-div-card-img card-img-top"
                      alt="..."
                    />
                    <div class="forth-div-card-body">
                      <p class="forth-div-card-header">
                        Fareed Sylvester{" "}
                        <span class="forth-div-card-icon">
                          <i class="fa-solid fa-code"></i>
                        </span>
                      </p>
                      <p class="forth-div-card-sub-header">Web developer</p>
                    </div>
                  </div>
                </div>
                <div class="col-12 col-md-6 col-lg-3">
                  <div class="forth-div-card card">
                    <img
                      src="images\landing-page-images\writing-instructor.jpg"
                      class="forth-div-card-img card-img-top"
                      alt="landing page image"
                    />
                    <div class="forth-div-card-body">
                      <p class="forth-div-card-header">
                        Isiah Vincent{" "}
                        <span class="forth-div-card-icon">
                          <i class="fa-solid fa-marker"></i>
                        </span>
                      </p>
                      <p class="forth-div-card-sub-header">Writer</p>
                    </div>
                  </div>
                </div>
                <div class="col-12 col-md-6 col-lg-3">
                  <div class="forth-div-card card">
                    <img
                      src="images\landing-page-images\business-instructure.jpg"
                      class="forth-div-card-img card-img-top"
                      alt="..."
                    />
                    <div class="forth-div-card-body">
                      <p class="forth-div-card-header">
                        Aaron Abraham{" "}
                        <span class="forth-div-card-icon">
                          <i class="fa-solid fa-user-tie"></i>
                        </span>
                      </p>
                      <p class="forth-div-card-sub-header">Businessman</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          {/* <!-- FORTH DIV END  -->

    <!-- FIFTH DIV START  --> */}
          <div class="fifth-div container">
            <div class="row">
              <div class="col-md-12 col-lg-6 fifth-div-col0">
                <img
                  class="fifth-div-img"
                  src="images\landing-page-images\track-learning.gif"
                  alt="scale-up.jpg"
                />
              </div>
              <div class="col-md-12 col-lg-6 fifth-div-col1">
                <p class="section-header fifth-div-header">
                  Track your learning and impove yourself more
                </p>
                <p class="section-text fifth-div-text">
                  Online learning allows the student and teacher to set their
                  own learning pace, and there's the added flexibility of
                  setting a schedule tat fits everyone.
                </p>
                <Link href="/Signup">
                  <button type="button" class="nav-button try-now-button">
                    <i class="fa-solid fa-fade fa-plus fifth-div-icon"></i>
                    Enroll now
                  </button>
                </Link>
              </div>
            </div>
          </div>
          {/* <!-- FIFTH DIV END  -->

    <!-- SIXTH DIV START  --> */}
          <div class="sixth-div container" id="testimonies">
            <p class="section-header sixth-div-header">
              What <span class="sixth-div-header-span">People</span> Say
            </p>

            {/* <!-- carousel  --> */}
            <section class="services">
              <div class="circle--slider">
                <div class="rotate--circle">
                  <ul class="circle--rotate" id="circle--rotate">
                    <li class="block">
                      <div class="sixth-div-img-div">
                        <img
                          class="six-div-img"
                          src="images\landing-page-images\face0.jpg"
                          alt=""
                        />
                        <span></span>
                      </div>
                    </li>
                    <li class="block">
                      <div class="sixth-div-img-div">
                        <img
                          class="six-div-img"
                          src="images\landing-page-images\face1.jpg"
                          alt=""
                        />
                        <span></span>
                      </div>
                    </li>
                    <li class="block">
                      <div class="sixth-div-img-div">
                        <img
                          class="six-div-img"
                          src="images\landing-page-images\face2.jpg"
                          alt=""
                        />
                        <span></span>
                      </div>
                    </li>
                    <li class="block">
                      <div class="sixth-div-img-div">
                        <img
                          class="six-div-img"
                          src="images\landing-page-images\face3.jpg"
                          alt=""
                        />
                        <span></span>
                      </div>
                    </li>
                    <li class="block">
                      <div class="sixth-div-img-div">
                        <img
                          class="six-div-img"
                          src="images\landing-page-images\face4.jpg"
                          alt=""
                        />
                        <span></span>
                      </div>
                    </li>
                  </ul>
                  <div class="animate-wrapper">
                    <div class="animate">
                      <div class="animate-img">
                        <div class="animate-img__in">
                          <div class="animate-more">
                            <div class="animate-title">
                              <p class="carousel-text">
                                This is the best place I have gotten an online
                                education from
                              </p>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="animate">
                      <div class="animate-img">
                        <div
                          class="animate-img__in"
                          data-image="&amp;auto=format&amp;fit=crop&amp;w=634&amp;q=80"
                        >
                          <div class="animate-more">
                            <div class="animate-title">
                              <p class="carousel-text">
                                This web portal is too soft for real. The web
                                developer should be paid more
                              </p>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="animate">
                      <div class="animate-img">
                        <div
                          class="animate-img__in"
                          data-image="&amp;auto=format&amp;fit=crop&amp;w=614&amp;q=80"
                        >
                          <div class="animate-more">
                            <div class="animate-title">
                              <p class="carousel-text">
                                At this point, I believe Fareed is not only
                                good. He is the best
                              </p>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="animate">
                      <div class="animate-img">
                        <div
                          class="animate-img__in"
                          data-image="&amp;auto=format&amp;fit=crop&amp;w=1350&amp;q=80"
                        >
                          <div class="animate-more">
                            <div class="animate-title">
                              <p class="carousel-text">
                                In need of quality education to study abroad.
                                Use this web portal
                              </p>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="animate">
                      <div class="animate-img">
                        <div
                          class="animate-img__in"
                          data-image="&amp;auto=format&amp;fit=crop&amp;w=634&amp;q=80"
                        >
                          <div class="animate-more">
                            <div class="animate-title">
                              <p class="carousel-text">
                                Finally, a good place to gain international
                                level standard knowledge
                              </p>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </section>
          </div>
          {/* <!-- carousel  -->
    <!-- SIXTH DIV END  -->

    <!-- SEVENTH DIV START  --> */}
          <div class="seventh-div container">
            <div class="seventh-div-header-div">
              <p class="seventh-div-header">
                Register today and get credible information, latest news,
                courses, resources and alot more what{" "}
                <span class="seventh-div-logo">
                  <span class="seventh-logo-span0">Pass</span>
                  <i class="fa-solid fa-circle-check seventh-logo-icon"></i>
                  <span class="seventh-logo-span0">mark</span>
                </span>{" "}
                has to offer.
              </p>
            </div>
            <div class="row">
              <div class="seventh-div-col0 col-md">
                <img
                  class="seventh-div-img"
                  src="images\landing-page-images\register-gif.gif"
                  alt="register-gif"
                />
              </div>
              <div class="seventh-div-col1 col-md">
                <Link href="/Signup">
                  <button type="button" class="nav-button seventh-div-button">
                    Register now
                  </button>
                </Link>
              </div>
            </div>
          </div>
          {/* <!-- SEVENTH DIV END  --> */}
        </section>
      </main>
    </>
  );
}
